language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: black-duck-software
    token:
      secure: CoH3hSDSeHGcdJZv5OhRxOiprnK5oyq4iDfqSWMbJ+sviPy4oH0pQiLLeqoCANFD9MoznvQwLNTnp7zjoaYG4juD91d7TTwVAJ9aZKxLD7/mEzhhiKWwWSgnUBMRd8gRAJC2rigvOPr1jclXSRUpIUHkPXd+3WC2HYsQODbgTFNCaq2QOS0Ywvwg8XJKuz/c6I0iEtgkgpebsw9zB7v/zCmjFcCkBQGWWDBD+aE7t9LR6NVQjXJioPXWyfnJmKdyk1bJVpTyLogqkDnWUskwqbjnJYVA8oPrIeaC7sHgzpGfWwFptNFFyYcMnYqwLeVWzUaza6FIz1wgGrsCofvkz6ZT6pSr5cKnOxavxbIeakho9Esdx6ncXQ8vTR5fD4yAj4LuIoqChy5fvJCrc8EtZ1li7Cw8FHhBgJUn8GJVsDMNIFsdOmZf5owoh3lQqb43oOWTTaV+Cvt4U0PGlz/mVyps01T4gQjpUsadNXmGfxUtsYOz/qNMTmLm0yqwzOrs3Gx+/kRHNsCfLneWo+6TST6q24paEuS8rcpFsChlBAajMKXBVHQRikTSsws4R8Y99BbqmI1Q4wuBTt4m77nonz9HhnDytqhm9uLFQKLTSPxpYTQAySbLYw8bhDe3eKhyMd519JeF7VEY95MzE9rNhC5ooYLQFz1AryfjW43kO2M=
jdk:
  - openjdk8
notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - psantos@blackducksoftware.com
      - gkillough@blackducksoftware.com
      - jrichard@blackducksoftware.com
      - bmandel@blackducksoftware.com
script:
  - mvn clean package
after_success:
  - export DETECT_MAVEN_SCOPE=runtime
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
